services:
  - type: web
    name: cbt-php-argon-v2
    env: docker
    plan: free
    buildCommand: docker build -t cbt-php-argon-v2 .
    startCommand: docker run -p 10000:80 cbt-php-argon-v2
    autoDeploy: true
